component: website
name: nocode-admin-frontend
app: nocode-admin-frontend

inputs:
  region: ${env:REGION}
  bucketName: nocode-admin-frontend
  protocol: https
  src:
    src: ./
    hook: npm run build
    dist: ./dist
    envPath: ./
    index: index.html
    error: index.html
  env:
    # get api url after below api service deployed.
    apiUrl: ${output:${stage}:${app}:nocode-admin-api.apigw.url}
